//go:build tools

package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"regexp"
	"sort"
	"strings"
	"unicode"

	"github.com/dave/jennifer/jen"
)

type MetaModel struct {
	MetaData      map[string]any     `json:"metaData"`
	Requests      []MetaRequest      `json:"requests"`
	Notifications []MetaNotification `json:"notifications"`
	Enumerations  []MetaEnum         `json:"enumerations"`
	Structures    []MetaStructure    `json:"structures"`
	TypeAliases   []MetaTypeAlias    `json:"typeAliases"`
}

type MetaRequest struct {
	Documentation       string `json:"documentation"`
	MessageDirection    string `json:"messageDirection"`
	Method              string `json:"method"`
	Params              any    `json:"params"`
	PartialResult       any    `json:"partialResult"`
	RegistrationOptions any    `json:"registrationOptions"`
	Result              any    `json:"result"`
	Since               string `json:"since"`
}

type MetaNotification struct {
	Documentation       string `json:"documentation"`
	MessageDirection    string `json:"messageDirection"`
	Method              string `json:"method"`
	Params              any    `json:"params"`
	RegistrationOptions any    `json:"registrationOptions"`
	Since               string `json:"since"`
}

type MetaEnum struct {
	Type                 any    `json:"type"`
	Documentation        string `json:"documentation"`
	Name                 string `json:"name"`
	Since                string `json:"since"`
	SupportsCustomValues bool   `json:"supportsCustomValues"`
	Values               []any  `json:"values"`
}

type MetaStructure struct {
	Documentation string `json:"documentation"`
	Extends       []any  `json:"extends"`
	Mixins        []any  `json:"mixins"`
	Name          string `json:"name"`
	Properties    []any  `json:"properties"`
}

type MetaTypeAlias struct {
	Documentation string `json:"documentation"`
	Name          string `json:"name"`
	Type          any    `json:"type"`
}

func methodConstName(method, direction string) string {
	// Remove all non-alphanumeric characters and capitalize each segment
	// Always capitalize the first alphanumeric character
	var b strings.Builder
	capitalizeNext := true
	for _, r := range method {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			if capitalizeNext {
				b.WriteRune(unicode.ToUpper(r))
				capitalizeNext = false
			} else {
				b.WriteRune(r)
			}
		} else {
			capitalizeNext = true
		}
	}
	// Ensure at least one character after prefix
	if b.Len() == 0 {
		return "MethodUnknown"
	}
	prefix := "Method"
	if direction == "serverToClient" {
		prefix = "Server"
	}
	return prefix + b.String()
}

func sanitizeDoc(doc string) string {
	// Remove newlines and excessive whitespace for single-line doc comments
	re := regexp.MustCompile(`\s+`)
	return re.ReplaceAllString(strings.TrimSpace(doc), " ")
}

func TrimVersion(s string) string {
	// 1) ^(\d+\.\d+(?:\.\d+)?)   ⇒ capture "X.Y" or "X.Y.Z" at the very start
	re := regexp.MustCompile(`^(\d+\.\d+(?:\.\d+)?)`)
	match := re.FindStringSubmatch(s)
	if match == nil {
		return "" // no version found
	}
	v := match[1]
	parts := strings.Split(v, ".")
	if len(parts) == 2 {
		// no patch component, add ".0"
		v += ".0"
	}
	return v
}

func generateMethodConsts(requests []MetaRequest, notifications []MetaNotification, outPath string) error {
	type methodInfo struct {
		ConstName string
		Method    string
		Doc       string
		Since     string
	}
	var methods []methodInfo
	for _, req := range requests {
		constName := methodConstName(req.Method, req.MessageDirection)
		methods = append(methods, methodInfo{
			ConstName: constName,
			Method:    req.Method,
			Doc:       sanitizeDoc(req.Documentation),
			Since:     TrimVersion(req.Since),
		})
	}
	for _, notif := range notifications {
		methods = append(methods, methodInfo{
			ConstName: methodConstName(notif.Method, notif.MessageDirection),
			Method:    notif.Method,
			Doc:       sanitizeDoc(notif.Documentation),
			Since:     TrimVersion(notif.Since),
		})
	}
	// Sort by constant name for stable output
	sort.Slice(methods, func(i, j int) bool {
		return methods[i].ConstName < methods[j].ConstName
	})

	f := jen.NewFile("protocol")
	f.HeaderComment("Code generated by genprotocol. DO NOT EDIT.")
	f.Comment("LSP method names as Go constants.")
	f.Line()
	f.Type().Id("Method").Op("=").String().Comment("LSP method names as Go constants.")
	consts := make([]jen.Code, 0, len(methods))
	for _, m := range methods {
		if m.Doc != "" && m.Doc != ("@since "+m.Since) {
			consts = append(consts, jen.Comment(m.Doc))
		}

		if m.Since == "" {
			m.Since = "<3.16.0"
		}

		consts = append(consts, jen.Comment("@since "+m.Since))
		consts = append(consts, jen.Id(m.ConstName).Op("=").Qual("", "Method").Call(jen.Lit(m.Method)))
		consts = append(consts, jen.Line())
	}
	f.Const().Defs(consts...)

	return f.Save(outPath)
}

func main() {
	// Fetch the metamodel from a URL (in memory)
	const metaModelURL = "https://raw.githubusercontent.com/microsoft/language-server-protocol/91cb771e0731fd0afda2972839830916ad586e0e/_specifications/lsp/3.17/metaModel/metaModel.json"
	resp, err := http.Get(metaModelURL)
	if err != nil {
		log.Fatalf("failed to fetch metamodel from URL: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		log.Fatalf("failed to fetch metamodel: HTTP %d", resp.StatusCode)
	}
	data, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatalf("failed to read metamodel response: %v", err)
	}
	var model MetaModel
	if err := json.Unmarshal(data, &model); err != nil {
		log.Fatalf("failed to unmarshal metamodel: %v", err)
	}
	fmt.Printf("Requests: %d\n", len(model.Requests))
	fmt.Printf("Notifications: %d\n", len(model.Notifications))
	fmt.Printf("Enumerations: %d\n", len(model.Enumerations))
	fmt.Printf("Structures: %d\n", len(model.Structures))
	fmt.Printf("TypeAliases: %d\n\n", len(model.TypeAliases))

	// Generate method constants file
	outPath := "methods_gen.go"
	if err := generateMethodConsts(model.Requests, model.Notifications, outPath); err != nil {
		log.Fatalf("failed to generate method constants: %v", err)
	}
	fmt.Printf("Generated %s\n", outPath)
}
