// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// go generate

package protocol

import (
	glsp "github.com/tliron/glsp"
	translation "github.com/tliron/glsp/protocol/translation"
)

func (h *Handler_317) GetMethodMap() map[Method]glsp.HandlerInterface {
	h.lock.Lock()
	defer h.lock.Unlock()
	if h.handlerMap == nil {
		h.handlerMap = map[Method]glsp.HandlerInterface{
			MethodCallHierarchyIncomingCalls:          translation.NewTypedHandler(h.CallHierarchyIncomingCalls),
			MethodCallHierarchyOutgoingCalls:          translation.NewTypedHandler(h.CallHierarchyOutgoingCalls),
			MethodCancelRequest:                       translation.NewNotificationHandler(h.CancelRequest),
			MethodCodeActionResolve:                   translation.NewTypedHandler(h.CodeActionResolve),
			MethodCodeLensResolve:                     translation.NewTypedHandler(h.CodeLensResolve),
			MethodCompletionItemResolve:               translation.NewTypedHandler(h.CompletionItemResolve),
			MethodDocumentLinkResolve:                 translation.NewTypedHandler(h.DocumentLinkResolve),
			MethodExit:                                translation.NewContextOnlyHandler(h.Exit),
			MethodInitialize:                          translation.NewTypedHandler(h.Initialize),
			MethodInitialized:                         translation.NewNotificationHandler(h.Initialized),
			MethodProgress:                            translation.NewNotificationHandler(h.Progress),
			MethodSetTrace:                            translation.NewNotificationHandler(h.SetTrace),
			MethodShutdown:                            translation.NewContextOnlyHandler(h.Shutdown),
			MethodTextDocumentCodeAction:              translation.NewTypedHandler(h.TextDocumentCodeAction),
			MethodTextDocumentCodeLens:                translation.NewTypedHandler(h.TextDocumentCodeLens),
			MethodTextDocumentColorPresentation:       translation.NewTypedHandler(h.TextDocumentColorPresentation),
			MethodTextDocumentCompletion:              translation.NewTypedHandler(h.TextDocumentCompletion),
			MethodTextDocumentDeclaration:             translation.NewTypedHandler(h.TextDocumentDeclaration),
			MethodTextDocumentDefinition:              translation.NewTypedHandler(h.TextDocumentDefinition),
			MethodTextDocumentDiagnostic:              translation.NewTypedHandler(h.TextDocumentDiagnostic),
			MethodTextDocumentDidChange:               translation.NewNotificationHandler(h.TextDocumentDidChange),
			MethodTextDocumentDidClose:                translation.NewNotificationHandler(h.TextDocumentDidClose),
			MethodTextDocumentDidOpen:                 translation.NewNotificationHandler(h.TextDocumentDidOpen),
			MethodTextDocumentDidSave:                 translation.NewNotificationHandler(h.TextDocumentDidSave),
			MethodTextDocumentDocumentColor:           translation.NewTypedHandler(h.TextDocumentDocumentColor),
			MethodTextDocumentDocumentHighlight:       translation.NewTypedHandler(h.TextDocumentDocumentHighlight),
			MethodTextDocumentDocumentLink:            translation.NewTypedHandler(h.TextDocumentDocumentLink),
			MethodTextDocumentDocumentSymbol:          translation.NewTypedHandler(h.TextDocumentDocumentSymbol),
			MethodTextDocumentFoldingRange:            translation.NewTypedHandler(h.TextDocumentFoldingRange),
			MethodTextDocumentFormatting:              translation.NewTypedHandler(h.TextDocumentFormatting),
			MethodTextDocumentHover:                   translation.NewTypedHandler(h.TextDocumentHover),
			MethodTextDocumentImplementation:          translation.NewTypedHandler(h.TextDocumentImplementation),
			MethodTextDocumentLinkedEditingRange:      translation.NewTypedHandler(h.TextDocumentLinkedEditingRange),
			MethodTextDocumentMoniker:                 translation.NewTypedHandler(h.TextDocumentMoniker),
			MethodTextDocumentOnTypeFormatting:        translation.NewTypedHandler(h.TextDocumentOnTypeFormatting),
			MethodTextDocumentPrepareCallHierarchy:    translation.NewTypedHandler(h.TextDocumentPrepareCallHierarchy),
			MethodTextDocumentPrepareRename:           translation.NewTypedHandler(h.TextDocumentPrepareRename),
			MethodTextDocumentRangeFormatting:         translation.NewTypedHandler(h.TextDocumentRangeFormatting),
			MethodTextDocumentReferences:              translation.NewTypedHandler(h.TextDocumentReferences),
			MethodTextDocumentRename:                  translation.NewTypedHandler(h.TextDocumentRename),
			MethodTextDocumentSelectionRange:          translation.NewTypedHandler(h.TextDocumentSelectionRange),
			MethodTextDocumentSemanticTokensFull:      translation.NewTypedHandler(h.TextDocumentSemanticTokensFull),
			MethodTextDocumentSemanticTokensFullDelta: translation.NewTypedHandler(h.TextDocumentSemanticTokensFullDelta),
			MethodTextDocumentSemanticTokensRange:     translation.NewTypedHandler(h.TextDocumentSemanticTokensRange),
			MethodTextDocumentSignatureHelp:           translation.NewTypedHandler(h.TextDocumentSignatureHelp),
			MethodTextDocumentTypeDefinition:          translation.NewTypedHandler(h.TextDocumentTypeDefinition),
			MethodTextDocumentWillSave:                translation.NewNotificationHandler(h.TextDocumentWillSave),
			MethodTextDocumentWillSaveWaitUntil:       translation.NewTypedHandler(h.TextDocumentWillSaveWaitUntil),
			MethodWindowWorkDoneProgressCancel:        translation.NewNotificationHandler(h.WindowWorkDoneProgressCancel),
			MethodWorkspaceDidChangeConfiguration:     translation.NewNotificationHandler(h.WorkspaceDidChangeConfiguration),
			MethodWorkspaceDidChangeWatchedFiles:      translation.NewNotificationHandler(h.WorkspaceDidChangeWatchedFiles),
			MethodWorkspaceDidChangeWorkspaceFolders:  translation.NewNotificationHandler(h.WorkspaceDidChangeWorkspaceFolders),
			MethodWorkspaceDidCreateFiles:             translation.NewNotificationHandler(h.WorkspaceDidCreateFiles),
			MethodWorkspaceDidDeleteFiles:             translation.NewNotificationHandler(h.WorkspaceDidDeleteFiles),
			MethodWorkspaceDidRenameFiles:             translation.NewNotificationHandler(h.WorkspaceDidRenameFiles),
			MethodWorkspaceExecuteCommand:             translation.NewTypedHandler(h.WorkspaceExecuteCommand),
			MethodWorkspaceSymbol:                     translation.NewTypedHandler(h.WorkspaceSymbol),
			MethodWorkspaceWillCreateFiles:            translation.NewTypedHandler(h.WorkspaceWillCreateFiles),
			MethodWorkspaceWillDeleteFiles:            translation.NewTypedHandler(h.WorkspaceWillDeleteFiles),
			MethodWorkspaceWillRenameFiles:            translation.NewTypedHandler(h.WorkspaceWillRenameFiles),
		}
	}
	return h.handlerMap
}
func (h *Handler_317) IsInitialized() bool {
	h.lock.Lock()
	defer h.lock.Unlock()
	return h.initialized
}
func (h *Handler_317) SetInitialized(initialized bool) {
	h.lock.Lock()
	defer h.lock.Unlock()
	h.initialized = initialized
}
func (h *Handler_317) GetVersion() glsp.LspProtocolVersion {
	return glsp.Protocol_317
}
