//go:build tools

package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strings"

	"github.com/dave/jennifer/jen"
)

type FieldInfo struct {
	FieldName   string
	MethodName  string
	HandlerType string
}

func main() {
	if len(os.Args) != 2 {
		log.Fatal("Usage: go run gen_methodmap.go <handler_file_prefix>")
	}

	handlerPrefix := os.Args[1]
	filename := handlerPrefix + ".go"

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
	if err != nil {
		log.Fatalf("Failed to parse file: %v", err)
	}

	var handlerStruct *ast.StructType
	var handlerName string
	// Find the handler struct
	for _, decl := range file.Decls {
		if genDecl, ok := decl.(*ast.GenDecl); ok && genDecl.Tok == token.TYPE {
			for _, spec := range genDecl.Specs {
				if typeSpec, ok := spec.(*ast.TypeSpec); ok {
					if structType, ok := typeSpec.Type.(*ast.StructType); ok {
						if strings.HasPrefix(typeSpec.Name.Name, "Handler_") {
							handlerStruct = structType
							handlerName = typeSpec.Name.Name
							break
						}
					}
				}
			}
		}
	}

	if handlerStruct == nil {
		log.Fatal("Handler struct not found")
	}

	// Parse struct fields and determine their types
	var fields []FieldInfo
	for _, field := range handlerStruct.Fields.List {
		if field.Names == nil {
			// Embedded field (like common_handler)
			continue
		}

		for _, name := range field.Names {
			fieldName := name.Name
			fieldType := getFieldType(field.Type)

			// Skip non-handler fields
			if !isHandlerField(fieldType) {
				continue
			}

			methodName := "Method" + fieldName
			handlerType := determineHandlerType(fieldType)

			fields = append(fields, FieldInfo{
				FieldName:   fieldName,
				MethodName:  methodName,
				HandlerType: handlerType,
			})
		}
	}

	// Generate the GetMethodMap function
	generateGetMethodMap(handlerName, fields)
}

func getFieldType(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.IndexExpr:
		return fmt.Sprintf("%s[%s]", getFieldType(t.X), getFieldType(t.Index))
	case *ast.IndexListExpr:
		var indices []string
		for _, index := range t.Indices {
			indices = append(indices, getFieldType(index))
		}
		return fmt.Sprintf("%s[%s]", getFieldType(t.X), strings.Join(indices, ", "))
	default:
		return ""
	}
}

func isHandlerField(fieldType string) bool {
	return strings.Contains(fieldType, "NotificationFunc") ||
		strings.Contains(fieldType, "RequestFunc") ||
		strings.Contains(fieldType, "ContextOnlyFunc")
}

func determineHandlerType(fieldType string) string {
	switch {
	case strings.Contains(fieldType, "NotificationFunc"):
		return "NewNotificationHandler"
	case strings.Contains(fieldType, "RequestFunc"):
		return "NewTypedHandler"
	case strings.Contains(fieldType, "ContextOnlyFunc"):
		return "NewContextOnlyHandler"
	}
	return ""
}

func generateGetMethodMap(handlerName string, fields []FieldInfo) {
	base := strings.ToLower(strings.TrimPrefix(handlerName, "Handler_"))
	outputFile := base + "_method_gen.go"

	f := jen.NewFile("protocol")
	f.HeaderComment("Code generated by go generate; DO NOT EDIT.")
	f.HeaderComment("This file was generated by robots at")
	f.HeaderComment("// go generate")

	// func (h *Handler_X) GetMethodMap() map[Method]glsp.HandlerInterface
	f.Func().
		Params(jen.Id("h").Op("*").Id(handlerName)).
		Id("GetMethodMap").
		Params().
		Params(jen.Map(jen.Id("Method")).Qual("github.com/tliron/glsp", "HandlerInterface")).
		Block(
			jen.Id("h").Dot("lock").Dot("Lock").Call(),
			jen.Defer().Id("h").Dot("lock").Dot("Unlock").Call(),
			jen.If(jen.Id("h").Dot("handlerMap").Op("==").Nil()).Block(
				jen.Id("h").Dot("handlerMap").Op("=").Map(
					jen.Id("Method"),
				).Qual(
					"github.com/tliron/glsp", "HandlerInterface",
				).Values(
					jen.DictFunc(func(d jen.Dict) {
						for _, field := range fields {
							d[jen.Id(field.MethodName)] = jen.
								Qual("github.com/tliron/glsp/protocol/translation", field.HandlerType).
								Call(jen.Id("h").Dot(field.FieldName))
						}
					}),
				),
			),
			jen.Return(jen.Id("h").Dot("handlerMap")),
		)

	// func (h *Handler_X) IsInitialized() bool
	f.Func().
		Params(jen.Id("h").Op("*").Id(handlerName)).
		Id("IsInitialized").
		Params().
		Params(jen.Bool()).
		Block(
			jen.Id("h").Dot("lock").Dot("Lock").Call(),
			jen.Defer().Id("h").Dot("lock").Dot("Unlock").Call(),
			jen.Return(jen.Id("h").Dot("initialized")),
		)

	// func (h *Handler_X) SetInitialized(initialized bool)
	f.Func().
		Params(jen.Id("h").Op("*").Id(handlerName)).
		Id("SetInitialized").
		Params(jen.Id("initialized").Bool()).
		Block(
			jen.Id("h").Dot("lock").Dot("Lock").Call(),
			jen.Defer().Id("h").Dot("lock").Dot("Unlock").Call(),
			jen.Id("h").Dot("initialized").Op("=").Id("initialized"),
		)

	// func (h *Handler_X) GetVersion() glsp.LspProtocolVersion
	f.Func().
		Params(jen.Id("h").Op("*").Id(handlerName)).
		Id("GetVersion").
		Params().
		Params(jen.Qual("github.com/tliron/glsp", "LspProtocolVersion")).
		Block(
			jen.Return(jen.Qual("github.com/tliron/glsp", "Protocol_"+base)),
		)

	if err := f.Save(outputFile); err != nil {
		log.Fatalf("Failed to write output file: %v", err)
	}
	fmt.Printf("Generated %s\n", outputFile)
}
