name: "staticcheck"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  staticcheck:
    name: "staticcheck"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: dominikh/staticcheck-action@v1
      with:
        version: "latest"
